# mandatory (#mandatory), optional (#optional).
# The overall format is standard TOML format, v0.5.0.
modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/BrassAmber-Mods/Brass_Geodes/issues"
[[mods]]
    modId="${mod_id}"
    version="${mod_version}" #mandatory
    displayName="${mod_name}" #mandatory
    displayURL="https://www.curseforge.com/minecraft/mc-mods/brassgeodes"
    logoFile="ring_amethyst.png"
    credits=" BrassMcrafty for all textures, Milamber for code"
    authors="${mod_authors}" #optional
    description='''${mod_description}'''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.brass_geodes]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
